package br.com.dominio.desafiocars.Model;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;


@Entity
@NoArgsConstructor
@Getter
@Setter
@Data
@ToString
@EqualsAndHashCode
@DynamoDBTable(tableName = "Car")
public class ModelEntityCar {

    @Id
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private Long _id;
    private boolean uniqueItems = true;
    private String title;
    private String brand;
    private String price;
    private Integer age;

}
